development:
  adapter: postgresql
  encoding: unicode
  database: helixx_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: helixx_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: helixx_production
  pool: 5
